# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ca_smoothing', [dirname(__file__)])
        except ImportError:
            import _ca_smoothing
            return _ca_smoothing
        if fp is not None:
            try:
                _mod = imp.load_module('_ca_smoothing', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ca_smoothing = swig_import_helper()
    del swig_import_helper
else:
    import _ca_smoothing
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def new_intp():
  return _ca_smoothing.new_intp()
new_intp = _ca_smoothing.new_intp

def copy_intp(*args):
  return _ca_smoothing.copy_intp(*args)
copy_intp = _ca_smoothing.copy_intp

def delete_intp(*args):
  return _ca_smoothing.delete_intp(*args)
delete_intp = _ca_smoothing.delete_intp

def intp_assign(*args):
  return _ca_smoothing.intp_assign(*args)
intp_assign = _ca_smoothing.intp_assign

def intp_value(*args):
  return _ca_smoothing.intp_value(*args)
intp_value = _ca_smoothing.intp_value

def new_floatp():
  return _ca_smoothing.new_floatp()
new_floatp = _ca_smoothing.new_floatp

def copy_floatp(*args):
  return _ca_smoothing.copy_floatp(*args)
copy_floatp = _ca_smoothing.copy_floatp

def delete_floatp(*args):
  return _ca_smoothing.delete_floatp(*args)
delete_floatp = _ca_smoothing.delete_floatp

def floatp_assign(*args):
  return _ca_smoothing.floatp_assign(*args)
floatp_assign = _ca_smoothing.floatp_assign

def floatp_value(*args):
  return _ca_smoothing.floatp_value(*args)
floatp_value = _ca_smoothing.floatp_value

def new_doublep():
  return _ca_smoothing.new_doublep()
new_doublep = _ca_smoothing.new_doublep

def copy_doublep(*args):
  return _ca_smoothing.copy_doublep(*args)
copy_doublep = _ca_smoothing.copy_doublep

def delete_doublep(*args):
  return _ca_smoothing.delete_doublep(*args)
delete_doublep = _ca_smoothing.delete_doublep

def doublep_assign(*args):
  return _ca_smoothing.doublep_assign(*args)
doublep_assign = _ca_smoothing.doublep_assign

def doublep_value(*args):
  return _ca_smoothing.doublep_value(*args)
doublep_value = _ca_smoothing.doublep_value

def new_boolp():
  return _ca_smoothing.new_boolp()
new_boolp = _ca_smoothing.new_boolp

def copy_boolp(*args):
  return _ca_smoothing.copy_boolp(*args)
copy_boolp = _ca_smoothing.copy_boolp

def delete_boolp(*args):
  return _ca_smoothing.delete_boolp(*args)
delete_boolp = _ca_smoothing.delete_boolp

def boolp_assign(*args):
  return _ca_smoothing.boolp_assign(*args)
boolp_assign = _ca_smoothing.boolp_assign

def boolp_value(*args):
  return _ca_smoothing.boolp_value(*args)
boolp_value = _ca_smoothing.boolp_value

def ca_smoothing(*args):
  return _ca_smoothing.ca_smoothing(*args)
ca_smoothing = _ca_smoothing.ca_smoothing

def get_sphere():
  return _ca_smoothing.get_sphere()
get_sphere = _ca_smoothing.get_sphere


